### PR TITLE
Add last and avg aggregations

### PR DESCRIPTION
**Pull request by LLIyRiK**
The drop-down list is extended to offer, besides min, max and total values, the average value and the last received value.

image

### CODE REVIEW

**Comment by TomerAmirV** [comment]
Hi!
Thanks for contributing!

I like your change but I have one small issue with it:

The default option `None` does the same thing as the `Last` option you added.
Your name makes more sense, but there shouldn't be this duplication.

Please remove the `None` option, and make the `Last` option the default and I will merge it with our code.

**Comment by LLIyRiK** [comment]
Hi!
I believe that `None` grabs first point from `datapoints` (as I can see in the code and in my debugger).
Also https://github.com/Vonage/Grafana_Status_panel#how-to-use says - `(None will just use the most first result)`.
Maybe it makes sense to rename `None` to `First`, and then make `Last` default option?

**Comment by TomerAmirV** [comment]
You're right. Makes sense. Please rename it, and update the tool tip.

**Comment by LLIyRiK** [comment]
@TomerAmirV,  done, please check

**Comment by TomerAmirV** [comment]
Looks good!
Approved

**Pull request merged**
