### PR TITLE
[Issue #34] Allow for interpolation in the measurement url

### PR DESCRIPTION
**Pull request by zot42**
I have already patched my local version and it worked with out issues

### CODE REVIEW

**Comment by TomerAmirV** [comment]
Hi, Thanks for contributing!

I'll be glad to merge your changes, but first I would like to ask two questions:
1. Could you explain the use case you are trying to support?
2. Also, isn't this change relevant for all URLs in the panel?

One last thing, you should commit also the compiled version of your change (in the `dist` folder) so that users who install the new version will be able to use your feature.

**Comment by zot42** [comment]
My use case is that I have a templated grafana dashboard that allows me to populate the region and instance. 

Using status panel with template variables, I use the multi-select feature for the instance which will then create a panel for each one. In the Measurement Url section, i have a url that references the above dashboard and I wanted to use the template variables to do so. 

By adding it, I can click on any one of the panels and get to the detailed dashboard for the instance I clicked on.

Before the change, the dashboard would open but the variables were $region and $instance.

I would say anywhere you are taking in text, you should support the template variables.

**Comment by zot42** [comment]
Sorry about not having the compiled version, I assumed you had a build process that would automagically create it. Are you just following the grafana-plugin guidelines, or do you have a prefered method?

Thanks so much for your time btw :)

**Comment by zot42** [comment]
do you want me to squash this into 1 pull request, or should I do another for the compiled version. 

Thanks much for your time

**Comment by TomerAmirV** [comment]
Yes, please put all changes in the same pull request.
I am just following the Grafana guidelines, but if just run `grunt` in the project folder, and then commit all changes it should be fine.

Don't forget to add your change to other links in the module.html file.

Thanks!

**Pull request closed without merging**
