### PR TITLE
Customise colours and whether applied to background, text or neither

### PR DESCRIPTION
**Pull request by PeteBa**
Hi,

I have submitted a pull request to add the following features into the status_panel plugin:
- Ability to select preferred ok/warn/crit/diasable colours.
- Option to apply colouring to either Background, Text or not at all.

In order to achieve this, I have made a number of modifications to the code as follows:
- Status_Panel.scss: Removed background_colour attribute from the *-state classes so that background_colours can be assigned dynamically through code logic.
- Editor.html: Added colour selectors for each of the OK, Warning, Critical and Disabled (the last is also used for No-Data) states.
- Editor.html: Allow the user to select how to apply the colours i.e. either as a Background colour, as Text colour or None for no colourising.
- Module.html: Use AngularJS markup to apply text coluring based on Panel and Metric state. Each metric is colourised based on the threshold level whereas the Panel is colourised based on the highest priority metric. Note that annotation URLs inherit the text colour of the associated metric rather than any Browser default style.
- Status_Ctrl.js: Consolidated Panel defaults (e.g. Flip time, Custom Colours, ...) into a Lodash default object to help maintainablity
- Status_Ctrl.js: Seperate logic to calculate Panel State (i.e. OK, Warn, Crit, Disable or NoData) from logic to apply class, text and background colour.

I have attached some pictures to illustrate the changes (yes, I'm using this for monitoring my home sprinklers rather than server ops 8). 
editor
panel

Pease let me know if this is usefull and/or if you would like me to make any changes. I see there are a few things in the PR log so happy to modify/rebase this if required.

Thanks, Peter

### CODE REVIEW

**Comment by PeteBa** [comment]
Hi, I have rebased this pull request onto the latest Master commits. In addition to the changes identified in the original comment, I have also slightly tweaked the crit/warn/ok/disabled colours so that the colorized text is more legible (i.e. a better contrast ratio). Again, happy to make any modification/fixes you think necessary. I have updated the other PR (Dates & Formats) but will hold off submitting it until this one has been reviewed. Thanks, Peter

**Comment by TomerAmirV** [comment]
Hi @PeteBa ,

Thanks again for your contribution 😄 
I will be glad to go over this pull request once we're done with #55

**Comment by nishantsharmajecrc** [comment]
any update on this one?

**Comment by PeteBa** [comment]
Hi, I have responded to the changes requested on PR 55 some time ago now. Could you please either provide further feedback or close the PR if not appropriate to merge. Many thanks. Peter

**Comment by TomerAmirV** [comment]
Hi,

Please resolve conflicts and I'll merge the change

**Comment by PeteBa** [comment]
Rebased to the current master. Thanks.

**Comment by TomerAmirV** [comment]
https://github.com/grafana/grafana-plugin-repository/pull/158

**Comment by PeteBa** [comment]
Thanks for taking this into the main branch. Much appreciated.

If you are pushing out a new release then please consider PR #73 . This is a one-line fix to the upgradeOldVersion() routine to ensure that it doesn't impact new series.

**Pull request merged**
