### PR TITLE
Added flipping on hover

### PR DESCRIPTION
**Pull request by LLIyRiK**
A quick overview of the overall systems' states with a flipping cards feature disclosing detailed values.

The panel now displays its state (OK / WARNING / FAILED / NO DATA) according to the set thresholds and flips to show the measurement value.

With WARNING / FAILED states, the panel flips automatically at regular intervals.
The OK state panels flip upon hover, while the NO DATA state panels remain unchanged.

The feature can be enabled/disabled in the checkbox.

NOTE: This PR depends on #23

out

### CODE REVIEW

**Comment by TomerAmirV** [comment]
Looks like a cool feature. I need to find the time to check it properly, so it might take me a while.
I'll get back to you as soon as I'm done.

**Comment by TomerAmirV** [comment]
Hi @LLIyRiK,
Sorry for all the conflicts, but I had to merge something that we need internally.
If you could merge the conflicts, I'll check changes ASAP.

**Comment by LLIyRiK** [comment]
Hi @TomerAmirV. Done.

**Comment by TomerAmirV** [comment]
@LLIyRiK @YehonatanVonage Good Job! 👏

**Comment by YehonatanVonage** [comment]
@LLIyRiK there were some bugs in the merge you did. I fixed them. Next time be very careful with the merge, and check all of the relevant new features added.

**Pull request merged**
