### PR TITLE
updated README.md with installation instructions

### PR DESCRIPTION
**Pull request by GPegel**

### CODE REVIEW

**Comment by TomerAmirV** [comment]
Hello and thanks for your contribution!

One small thing, the way to install is described in the Grafana website and is more simple. the way you described is probably better for debugging purposes only. I think it will be better to write that this way is for debugging purposes.

What do you think?

**Comment by GPegel** [comment]
I agree, I've changed the text.

**Comment by GPegel** [comment]
By the way, keep in mind that not everyone is able to download and install the plugin directly from the Grafana website due to firewall restrictions. In my case my servers at work are NOT connected directly to the internet. So if I want to install one of those plugins I have to side-load it on my own laptop and then copy it to a server. That's also the reason why I added this text.

**Comment by TomerAmirV** [comment]
Cool, I did not think of that.
I will merge it, but I'll ask Grafana to update the README displayed on their site on the next release.

**Pull request merged**
